# formats: htmlzip, pdf, epub
python:
  version: 3
  setup_py_install: true
  # pip_install: false
  # extra_requirements: []
requirements_file: docs/requirements.txt
conda:
  file: docs/conda.environment.yml
