name: conv_opt-docs
channels:
  - conda-forge
  - jjhelmus
  - defaults
dependencies:
  - cvxopt
  - cylp
  - cython
  - numpy
  - pip
  - python
  - sphinx
  - swig
  - sympy
  - pip:
    - configparser
    - sphinx_rtd_theme
    - robpol86-sphinxcontrib-googleanalytics
    - sphinxcontrib-bibtex
    - sphinxcontrib-spelling
    - swiglpk
