name: conv_opt-docs
channels:
  - conda-forge
  - jjhelmus
  - defaults
dependencies:
  - cvxopt
  - cylp
  - cython
  - numpy
  - pip
  - python>=3.6.4
  - sphinx
  - swig
  - sympy
  - pip:
    - configparser
    - sphinx_rtd_theme
    - robpol86_sphinxcontrib_googleanalytics
    - sphinxcontrib_bibtex
    - sphinxcontrib_spelling
    - swiglpk
